version: '3'

services:
  node-express-app:
    build: .
    ports:
      - '3000:3000'

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_HOST=node-express-app
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
